# Try catch

function funcao1()
{
    echo 'Entrei na função 1' . PHP_EOL;
    try{
    $arrayFixo = new SplFixedArray(2);
    $arrayFixo[0] = "Valor";
    } catch (RuntimeException $problema){
        echo "aconteceu um erro na função 1" . PHP_EOL;
    }
    //$divisao = intdiv(5, 0);
    funcao2();
    echo 'Saindo da função 1' . PHP_EOL;
}

# Pegando na pilha

function funcao1()
{
    echo 'Entrei na função 1' . PHP_EOL;
    try{
        funcao2();
    }catch (RuntimeException $problema){
        echo "Na função 1, eu resolvi o problema da função 2" . PHP_EOL;
    }
    echo 'Saindo da função 1' . PHP_EOL;
}

#Multiplas execuções

function funcao1()
{
    echo 'Entrei na função 1' . PHP_EOL;
    try{
    funcao2();
    } catch (RuntimeException | DivisionByZeroError $erroOuExcecao) {
        echo $erroOuExcecao->getMessage() . PHP_EOL; // traz a mensagem do problema
        echo $erroOuExcecao->getLine() . PHP_EOL; // vê a linha que aconteceu
       // echo $erroOuExcecao->getFile() . PHP_EOL; // vê qual o arquivo
       // echo $erroOuExcecao->getTrace() . PHP_EOL; //pega como um array
        echo $erroOuExcecao->getTraceAsString() . PHP_EOL; //pega formatado como string - trilha de execução até chegar aonde esse erro acoteceu

        //echo "Na função 1, eu resolvi o problema da função 2" . PHP_EOL;
    }
    echo 'Saindo da função 1' . PHP_EOL;
}